### ISSUE TITLE
Create a findOne repository in the project.

### ISSUE THREAD

**Issue by Mod5ied** [jmw5598/node-typescript-express-starter#16]
I had tried creating a findOne repository, while using an interface based on the assumed return value of the function. But I keep running into errors. Take a look:
 ![Screenshot (233).png](https://user-images.githubusercontent.com/53910072/182918101-4e29f73c-f85c-4b9f-81b6-45a46b33ddcd.png)

And here's the error:
![Screenshot (235).png](https://user-images.githubusercontent.com/53910072/182918186-3c181cd9-43d4-4b27-badd-f47a9c307061.png)

Here's my interface.repo.ts:
![Screenshot (236).png](https://user-images.githubusercontent.com/53910072/182918335-6f09a454-b605-456d-abd0-99d5993649a5.png)

**Comment by jmw5598** [comment]
In your tsconfig you probably have strict set to true.  If so you need to specify every return type for the method definitions in your `IRepo` interface.  TypeORMs repository method for `findOneBy` probably returns `T | null` (I'm not 100% sure, you'll have to look that up) so you need to specify the possibility of a null for your `IRepo` interface for `findSingle`.....`findSingle(id: number): Promise<T | null>`.

**Comment by Mod5ied** [comment]
But then.
While toggling off Strict resolves the issue, isn't that the main upper hand of using typescript.
I mean, doesn't it affect how typescript would run and type check the rest of the code?

**Comment by Mod5ied** [comment]
> In your tsconfig you probably have strict set to true.  If so you need to specify every return type for the method definitions in your `IRepo` interface.  TypeORMs repository method for `findOneBy` probably returns `T | null` (I'm not 100% sure, you'll have to look that up) so you need to specify the possibility of a null for your `IRepo` interface for `findSingle`.....`findSingle(id: number): Promise<T | null>`.

Thanks alot for the quick and concise response.
Keep being kind🤝🤝🙂
